### ISSUE TITLE
Sorry if I'm missing something

### ISSUE THREAD

**Issue by dvvvsh** [0xver/ether#1]
There isn't a lot of written information so I apologize for not knowing the answers. For account, is that mnemonic, wallet address, private key, keystore or?
also, is it possible to import private keys?

**Comment by 0xver** [comment]
This issue has been fixed in the latest version. The account is the wallet address.

Currently, you can only generate a wallet using `ether init` and it's strongly recommended you use a passphrase. The passphrase is generated by your own methods and is prompted each time you use your account. Leaving the passphrase empty allows you to import the mnemonic into MetaMask and other wallets without issue but this is only recommended for testnet purposes.

The main reason I didn't add an import feature was so the passphrase feature was emphasized. If the mnemonic is compromised, the passphrase would be needed to gain access to the correct seed.
